@startuml
package com.gerald.image.microservice {
  class ImageApplication {
    + ImageApplication()
    + main(args : String[]) {static}
  }
  class ImageController {
    + ImageController()
    + getImagePath() : String
  }
}
@enduml