#
# information-microservice - java-design-patterns
# Copyright © 2017 www.youbanban.com (yangqianhui@youbanban.com)
#
# This project belongs to Shanghai Run Great lmt information, you can not share, copy and do anything
# by these code!
#

server:
  port: 51515